# Generated by Django 3.2.16 on 2024-07-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_purpose', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
