# Generated by Django 3.2.16 on 2024-07-16 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('call_purpose', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='assistant_first_message',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='call',
            old_name='customer_number',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='call',
            name='analytics',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='lead_converted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='call',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='call_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='callsummary',
            name='call',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='call_summaries', to='call_purpose.call'),
        ),
    ]
