# Generated by Django 3.2.16 on 2024-06-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_purpose', '0002_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(max_length=255, unique=True)),
                ('caller_number', models.CharField(max_length=15)),
                ('callee_number', models.CharField(max_length=15)),
                ('call_status', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('transcript', models.TextField()),
                ('response', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('lead_name', models.CharField(blank=True, max_length=255, null=True)),
                ('discussion', models.TextField(blank=True, null=True)),
                ('cost_of_call', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
