# Generated by Django 3.2.16 on 2024-06-29 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('call_purpose', '0005_auto_20240629_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='call_purpose.call')),
            ],
        ),
    ]
