# Generated by Django 3.2.16 on 2024-07-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_purpose', '0006_callsummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
